
ALTER TABLE public.operational_task_settings
  ADD COLUMN IF NOT EXISTS alert_critical_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS alert_critical_delay_minutes int DEFAULT 15,
  ADD COLUMN IF NOT EXISTS alert_overdue_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS alert_overdue_delay_minutes int DEFAULT 10,
  ADD COLUMN IF NOT EXISTS alert_daily_summary_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS alert_daily_summary_time text DEFAULT '22:00',
  ADD COLUMN IF NOT EXISTS alert_daily_summary_target text DEFAULT 'gestor',
  ADD COLUMN IF NOT EXISTS alert_temperature_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS alert_browser_notifications boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS alert_whatsapp_number text,
  ADD COLUMN IF NOT EXISTS report_daily_content jsonb DEFAULT '["taxa_conclusao","atrasadas","destaque","criticos","turnos"]'::jsonb,
  ADD COLUMN IF NOT EXISTS report_weekly_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS report_weekly_day int DEFAULT 1,
  ADD COLUMN IF NOT EXISTS allow_late_completion boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS require_photo_default boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS default_max_duration_minutes int DEFAULT 60,
  ADD COLUMN IF NOT EXISTS allow_free_notes boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_countdown_timer boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS block_early_execution boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS min_pin_digits int DEFAULT 4,
  ADD COLUMN IF NOT EXISTS session_timeout_minutes int DEFAULT 30,
  ADD COLUMN IF NOT EXISTS sectors_config jsonb DEFAULT '[]'::jsonb;
