ALTER TABLE public.pdv_cashier_sessions
  ADD COLUMN IF NOT EXISTS total_credit numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_debit numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_voucher numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_change numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS declared_cash numeric,
  ADD COLUMN IF NOT EXISTS declared_credit numeric,
  ADD COLUMN IF NOT EXISTS declared_debit numeric,
  ADD COLUMN IF NOT EXISTS declared_pix numeric,
  ADD COLUMN IF NOT EXISTS declared_voucher numeric,
  ADD COLUMN IF NOT EXISTS cash_difference numeric,
  ADD COLUMN IF NOT EXISTS credit_difference numeric,
  ADD COLUMN IF NOT EXISTS debit_difference numeric,
  ADD COLUMN IF NOT EXISTS pix_difference numeric,
  ADD COLUMN IF NOT EXISTS voucher_difference numeric,
  ADD COLUMN IF NOT EXISTS justification_cash text,
  ADD COLUMN IF NOT EXISTS justification_credit text,
  ADD COLUMN IF NOT EXISTS justification_debit text,
  ADD COLUMN IF NOT EXISTS justification_pix text,
  ADD COLUMN IF NOT EXISTS justification_voucher text;