
ALTER TABLE public.pdv_products
  ADD COLUMN IF NOT EXISTS ncm TEXT,
  ADD COLUMN IF NOT EXISTS cest TEXT,
  ADD COLUMN IF NOT EXISTS cfop TEXT,
  ADD COLUMN IF NOT EXISTS origin TEXT,
  ADD COLUMN IF NOT EXISTS cst_icms TEXT,
  ADD COLUMN IF NOT EXISTS csosn TEXT,
  ADD COLUMN IF NOT EXISTS icms_rate NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS pis_cst TEXT,
  ADD COLUMN IF NOT EXISTS pis_rate NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS cofins_cst TEXT,
  ADD COLUMN IF NOT EXISTS cofins_rate NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS tax_unit TEXT,
  ADD COLUMN IF NOT EXISTS ean TEXT;
